spring.application.name=aprendendoafazerisso

server.port=8181

spring.datasource.url=jdbc:mysql://localhost:3306/helpdesk_training
spring.datasource.username=root
spring.datasource.password=123@Mudar

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

